name: Terraform Apply

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_INPUT: false

      # 🔑 Terraform variables (EXPLICIT MAPPING)
      TF_VAR_snowflake_account:  ${{ secrets.TF_VAR_SNOWFLAKE_ACCOUNT }}
      TF_VAR_snowflake_username: ${{ secrets.TF_VAR_SNOWFLAKE_USERNAME }}
      TF_VAR_snowflake_password: ${{ secrets.TF_VAR_SNOWFLAKE_PASSWORD }}
      TF_VAR_snowflake_role:     ${{ secrets.TF_VAR_SNOWFLAKE_ROLE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/243453074532/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "terraform-ci@project-d938e8ef-98b9-4e42-9e8.iam.gserviceaccount.com"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve